// Expo web post-export: installable manifest/icons + public-static-only worker.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const ROOT = path.resolve(__dirname, '..');
function listFiles(directory, prefix = '') {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
    const relative = prefix + entry.name;
    return entry.isDirectory() ? listFiles(path.join(directory, entry.name), relative + '/') : [relative];
  });
}
function allowedStaticFiles(files) {
  return files.filter(file => file === 'index.html' || file === 'favicon.ico' ||
    file === 'manifest.webmanifest' || /^icons\/icon-(192|512|180)\.png$/.test(file) ||
    /^_expo\/static\/.*\.(js|css)$/.test(file) ||
    /^assets\/.*\.(png|jpe?g|webp|svg|ttf|otf|woff2?)$/.test(file)).sort();
}
function buildWorker(version, files) {
  return `/* Generated by scripts/export_webapp.cjs. Public build assets only. */
'use strict';
const CACHE_PREFIX = 'scamgraph-public-shell-';
const CACHE = CACHE_PREFIX + ${JSON.stringify(version)};
const ASSETS = ${JSON.stringify(files.map(file => '/' + file))};
const ALLOWED = new Set(ASSETS);
self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Public resources are fetched without cookies. Never add runtime responses.
    await Promise.all(ASSETS.map(async url => {
      const response = await fetch(new Request(url, { credentials: 'omit', cache: 'reload', redirect: 'error' }));
      if (!response.ok || response.type !== 'basic') throw new Error('Public shell unavailable');
      await cache.put(url, response);
    }));
  })());
});
self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    for (const name of await caches.keys()) {
      if (name.startsWith(CACHE_PREFIX) && name !== CACHE) await caches.delete(name);
    }
    await self.clients.claim();
  })());
});
self.addEventListener('message', event => {
  if (event.data && event.data.type === 'ACTIVATE_UPDATE') self.skipWaiting();
});
self.addEventListener('fetch', event => {
  const request = event.request;
  const url = new URL(request.url);
  // API/auth/uploads/history/jobs/results are intentionally outside the allowlist.
  // Non-GET, credentials-bearing Authorization, OAuth query and foreign origins
  // pass directly to the browser network: never cache or synthesize their data.
  if (request.method !== 'GET' || request.headers.has('authorization') ||
      url.origin !== self.location.origin || url.search) return;
  const root = url.pathname === '/' || url.pathname === '/index.html';
  if (request.mode === 'navigate' && root) {
    event.respondWith(fetch(request).catch(async () => {
      try {
        const cached = await (await caches.open(CACHE)).match('/index.html');
        if (cached) return cached;
      } catch { /* Storage blocked/evicted: return an honest unavailable response. */ }
      return new Response('ScamGraph AI requires a connection for analysis. Reconnect and reload.', {
        status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'no-store' }
      });
    }));
    return;
  }
  if (!ALLOWED.has(url.pathname) || url.pathname === '/index.html') return;
  event.respondWith((async () => {
    try {
      const cached = await (await caches.open(CACHE)).match(url.pathname);
      if (cached) return cached;
    } catch { /* Cache storage unavailable: public assets still use the network. */ }
    return fetch(request);
  })());
});
`;
}
async function exportWebapp() {
  const appRoot = path.join(ROOT, 'app');
  const dist = path.join(appRoot, 'dist');
  const index = path.join(dist, 'index.html');
  if (!fs.existsSync(index)) throw new Error('Export Expo web first: app/dist/index.html is missing');
  const { generateImageAsync } = require('../app/node_modules/@expo/image-utils');
  const publicIcons = path.join(appRoot, 'public/icons');
  fs.mkdirSync(publicIcons, { recursive: true });
  fs.mkdirSync(path.join(dist, 'icons'), { recursive: true });
  for (const size of [192, 512, 180]) {
    const icon = await generateImageAsync({ projectRoot: appRoot, cacheType: 'scamgraph-pwa' }, {
      src: path.join(appRoot, 'assets/icon.png'), width: size, height: size,
      resizeMode: 'contain', removeTransparency: true, backgroundColor: '#ffffff'
    });
    const name = 'icon-' + size + '.png';
    fs.writeFileSync(path.join(publicIcons, name), icon.source);
    fs.writeFileSync(path.join(dist, 'icons', name), icon.source);
  }
  fs.copyFileSync(path.join(appRoot, 'public/manifest.webmanifest'), path.join(dist, 'manifest.webmanifest'));
  let html = fs.readFileSync(index, 'utf8');
  // Re-running the postprocessor is idempotent, including deterministic version.
  html = html.replace(/\n?<!-- scamgraph-pwa:start -->[\s\S]*?<!-- scamgraph-pwa:end -->\n?/g, '');
  const metadata = `<!-- scamgraph-pwa:start -->
<meta name="referrer" content="no-referrer" />
<link rel="manifest" href="/manifest.webmanifest" />
<meta name="theme-color" content="#0b1643" />
<meta name="mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-title" content="ScamGraph AI" />
<link rel="apple-touch-icon" href="/icons/icon-180.png" />
<!-- scamgraph-pwa:end -->`;
  if (!html.includes('</head>')) throw new Error('Expo export has no HTML head');
  html = html.replace(/<html lang="[^"]*">/, '<html lang="th">');
  html = html.replace('</head>', metadata + '</head>');
  fs.writeFileSync(index, html);
  const files = allowedStaticFiles(listFiles(dist));
  const digest = crypto.createHash('sha256');
  for (const file of files) digest.update(file).update(fs.readFileSync(path.join(dist, file)));
  const version = digest.digest('hex').slice(0, 16);
  const worker = buildWorker(version, files);
  fs.writeFileSync(path.join(dist, 'service-worker.js'), worker);
  fs.writeFileSync(path.join(dist, 'webapp-build.json'), JSON.stringify({
    version, public_asset_count: files.length, caches_private_data: false,
    offline_analysis: false, generated_at: new Date().toISOString()
  }, null, 2));
  console.log('Webapp ready:', files.length, 'public assets; version', version, '; private/API data never cached.');
}
module.exports = { allowedStaticFiles, buildWorker, exportWebapp };
if (require.main === module) exportWebapp().catch(error => { console.error(error.message); process.exitCode = 1; });
