'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { checkWebEnvironment } = require('./check_web_env.cjs');
const root = path.resolve(__dirname, '..');
const config = JSON.parse(fs.readFileSync(path.join(root, 'vercel.json'), 'utf8'));
assert.equal(config.outputDirectory, 'app/dist');
assert.equal(config.installCommand, 'npm ci --prefix app');
assert.match(config.buildCommand, /check_web_env\.cjs --production/);
assert.match(config.buildCommand, /build:web/);
const route = new RegExp('^' + config.rewrites[0].source + '$');
assert(route.test('/settings'));
assert(route.test('/'));
for (const url of ['/api', '/api/auth/me', '/api/reports/evidence/123', '/service-worker.js', '/manifest.webmanifest', '/icons/icon-512.png', '/_expo/static/js/web/file.js', '/assets/font.ttf']) assert(!route.test(url), url);
const header = (source, key) => config.headers.find(x => x.source === source).headers.find(x => x.key === key).value;
assert.match(header('/service-worker.js', 'Cache-Control'), /no-cache/);
assert.equal(header('/manifest.webmanifest', 'Content-Type'), 'application/manifest+json');
assert.deepEqual(checkWebEnvironment({ EXPO_PUBLIC_API_URL: 'https://api.scamgraph-production.com/api' }, true), []);
for (const value of ['', '/api', 'http://api.scamgraph-production.com/api', 'https://localhost/api', 'https://192.168.1.4/api', 'https://api.your-domain.example/api', 'https://example.com/api', 'https://user:secret@host.com/api', 'https://host.com/api?token=secret']) assert(checkWebEnvironment({ EXPO_PUBLIC_API_URL: value }, true).length, value);
const secret = 'never-print-this-value';
const errors = checkWebEnvironment({ EXPO_PUBLIC_API_URL: 'https://host.com/api', EXPO_PUBLIC_LINE_TOKEN: secret }, true);
assert(errors.length && !errors.join('').includes(secret));
console.log('Vercel deployment paths, API exclusions, PWA headers and public-env validation checks passed.');
