"""OIDC identities PKCE handoffs and opt-in LINE Messaging

Revision ID: a6b7a770c392
Revises: c5918a6294d3
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a6b7a770c392'
down_revision: Union[str, None] = 'c5918a6294d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_friendships',
    sa.Column('subject', sa.String(length=40), nullable=False),
    sa.Column('following', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('subject')
    )
    op.create_table('webhook_receipts',
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('line_subscriptions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('oauth_exchanges',
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('client_code_challenge', sa.String(length=43), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('intent', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code_hash')
    )
    op.create_index(op.f('ix_oauth_exchanges_expires_at'), 'oauth_exchanges', ['expires_at'], unique=False)
    op.create_index(op.f('ix_oauth_exchanges_user_id'), 'oauth_exchanges', ['user_id'], unique=False)
    op.create_table('oauth_states',
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('app_redirect_uri', sa.Text(), nullable=False),
    sa.Column('provider_redirect_uri', sa.Text(), nullable=False),
    sa.Column('client_code_challenge', sa.String(length=43), nullable=False),
    sa.Column('provider_code_verifier', sa.String(length=128), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('intent', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state_hash')
    )
    op.create_index(op.f('ix_oauth_states_expires_at'), 'oauth_states', ['expires_at'], unique=False)
    op.create_table('provider_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_provider_subject'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_provider')
    )
    op.create_index(op.f('ix_provider_identities_user_id'), 'provider_identities', ['user_id'], unique=False)
    op.create_table('line_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('history_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'history_id', name='uq_line_delivery_history')
    )
    op.create_index(op.f('ix_line_deliveries_history_id'), 'line_deliveries', ['history_id'], unique=False)
    op.create_index(op.f('ix_line_deliveries_user_id'), 'line_deliveries', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_deliveries_user_id'), table_name='line_deliveries')
    op.drop_index(op.f('ix_line_deliveries_history_id'), table_name='line_deliveries')
    op.drop_table('line_deliveries')
    op.drop_index(op.f('ix_provider_identities_user_id'), table_name='provider_identities')
    op.drop_table('provider_identities')
    op.drop_index(op.f('ix_oauth_states_expires_at'), table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index(op.f('ix_oauth_exchanges_user_id'), table_name='oauth_exchanges')
    op.drop_index(op.f('ix_oauth_exchanges_expires_at'), table_name='oauth_exchanges')
    op.drop_table('oauth_exchanges')
    op.drop_table('line_subscriptions')
    op.drop_table('webhook_receipts')
    op.drop_table('line_friendships')
    # ### end Alembic commands ###
